# Generated by Django 5.1.7 on 2025-04-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='date_time_end',
            field=models.DateTimeField(default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
